grailsVersion=7.2.0
grailsSpringSecurity=7.0.2
grailsSpringSecurityRest=7.0.2
quartz=4.0.1
solrj=9.10.1
tika=3.3.1
minaSshd=2.18.0
antlr4=4.13.2
protobufVersion=4.35.1
#protobufVersion=3.21.12
org.gradle.logging.level=info
org.gradle.parallel=true
org.gradle.workers.max=2
org.gradle.caching=false
org.gradle.daemon=false
#org.gradle.jvmargs=-Dfile.encoding=UTF-8 -XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders -Xmx4096m
taackUiVersion=0.7.6

exploded=true
jakartaMail=2.1.4
postgresJdbc=42.7.7
